### ISSUE TITLE
ReadFileInfoAsync Fails SSB

### ISSUE THREAD

**Issue by OliverVisual** [Tewr/BlazorFileReader#72]
**Describe the bug**
When calling ReadFileInfoAsync using Server Side Blazor Preview 8. You get "An exception occurred executing JS interop: The JSON value could not be converted to Blazor.FileReader.FileInfo. Path: $ | LineNumber: 0 | BytePositionInLine: 104.. See InnerException for more details."

Seems like JS is pulling info, but server.blazor.js errors.

**To Reproduce**
1. Call - var fileInfo = await file.ReadFileInfoAsync();
2. Click on - catch error

**Expected behavior**
It returns fileinfo

**Screenshots**

**Project type**
Server-side

**Environment**
 - Browser chrome
 - Version of Blazor.FileReader ( _14.19226
 - Version of .net sdk 3 preview 8
 
**Additional context**
Stacktrace

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntimeBase.<InvokeWithDefaultCancellation>d__13`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blazor.FileReader.FileReaderJsInterop.<GetFileInfoFromElement>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blazor.FileReader.FileReference.<ReadFileInfoAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisualBlazor.Pages.Qutes.View.<ReadFile>d__96.MoveNext() in E:\VisualApprovals\VAPortal3\Pages\Qutes\View.razor:line 948

**Comment by Tewr** [comment]
I need some more info on how to reproduce this. Can you post the code in your view?

**Comment by OliverVisual** [comment]
Hi,

It worked great in preview 7. Updated the nugget packages and the JS and TS files in wwwroot.

Code is simple usage as below and I'm selecting a PDF file.

ElementReference inputElement;

public async Task ReadFile()
    {​
        Output = string.Empty;​
        this.StateHasChanged();​
        var nl = Environment.NewLine;​
​
        if (PageDataForUpload != null)​
        {​
            PageDataForUpload.Clear();​
​
        }​
​
​
        foreach (var file in await fileReaderService.CreateReference(inputElement).EnumerateFilesAsync())​
        {​
            var fileInfo = await file.ReadFileInfoAsync();​
            Output += $"{nameof(IFileInfo)}.{nameof(fileInfo.Name)}: {fileInfo.Name}{nl}";​
            Output += $"{nameof(IFileInfo)}.{nameof(fileInfo.Size)}: {fileInfo.Size}{nl}";​
            Output += $"{nameof(IFileInfo)}.{nameof(fileInfo.Type)}: {fileInfo.Type}{nl}";​
            Output += $"{nameof(IFileInfo)}.{nameof(fileInfo.LastModifiedDate)}: {fileInfo.LastModifiedDate?.ToString() ?? "(N/A)"}{nl}";​
            Output += $"Reading file...";​
            this.StateHasChanged();

wwwroot looks like this.

[cid:3dc82079-6d19-4f6d-be60-74188027e7bf]

________________________________

**Comment by Tewr** [comment]
Looks fairly standard so the problem is more likely in your setup somewhere.  I haven't seen any problems with JSON serialization.

The [SSB demo](https://github.com/Tewr/BlazorFileReader/tree/master/src/Demo/Blazor.FileReader.ServerSide.Demo) works fine under preview8, try comparing your setup (wwwroot content, csproj, startup.cs etc) with the demo and see if there is any difference you can spot.

Your exception says there may be more details in the InnerException, you think you can catch it?

**Comment by OliverVisual** [comment]
Thanks mate,

Was the below, that was missing.

 app.Use(async (context, next) =>
            {​
                context.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;​
                await next.Invoke();​
            });

________________________________

**Comment by Tewr** [comment]
OK, sounds odd compared to the error you got, but I'm glad you got it working!

**Comment by OliverVisual** [comment]
Hi Mate,

I wasn't sure to post this as an issue or not?
I'm trying to upload large files and show a progress bar.

Is there a way using Server Side Blazor to get the progress from your control?

I tried a few different ways, but no luck.


________________________________

**Comment by Tewr** [comment]
Have a look  the samples. [This line](https://github.com/Tewr/BlazorFileReader/blob/58ae55a5c5737d08adf2350891eadbfe82a76bd9/src/Demo/Blazor.FileReader.Demo.Common/IndexCommon.razor#L50) can be easily switched to get the current stream position.

Something like this:
`<progress max=@max value=@value></progress>`

```
 max = fs.Length;
 while ((count = await fs.ReadAsync(buffer, 0, buffer.Length)) != 0)
 {
       value = fs.Position;
       this.StateHasChanged();
  }
```
